# Generated by Django 5.0.1 on 2024-06-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=25)),
                ('image', models.CharField(default='', max_length=250)),
                ('tarif', models.CharField(default='', max_length=50)),
                ('isBlocked', models.BooleanField(default=False)),
                ('duree', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=25)),
                ('email', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=25)),
                ('role', models.CharField(default='', max_length=12)),
                ('cin', models.CharField(default='', max_length=12)),
                ('isBlocked', models.BooleanField(default=False)),
                ('telephone', models.CharField(default='', max_length=14)),
                ('ministere', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=250)),
                ('biographie', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=250)),
                ('type', models.CharField(default='', max_length=25)),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=15, unique=True)),
                ('username', models.CharField(default='', max_length=25)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=250, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.CreateModel(
            name='ReferencePayement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debitPhone', models.CharField(default='', max_length=14)),
                ('creditPhone', models.CharField(default='', max_length=14)),
                ('value', models.CharField(default='', max_length=25)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeServices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(default='attente', max_length=25)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
